import {test} from 'node:test';
import assert from 'node:assert/strict';
import {existing as x,reader,runtime,boundFixture,p,id,enabled} from './helpers/commerce-existing-fixtures.mjs';
test('bound price edit sends changed native field only; no copy/media/tracking/stock',()=>{const {snapshot}=boundFixture();const plan=x.planBoundCommerceEdit(snapshot,{price:'550'});assert.deepEqual(plan.request.variables,{productId:snapshot.identity.productGid,variants:[{id:snapshot.identity.variantGid,price:'550.00'}]});assert.equal(plan.desired.tracked,true);assert.equal(plan.desired.protectedHash,snapshot.protectedHash);});
test('nulls and explicit false preserved; requiresShipping uses inventoryItem without tracking',()=>{const {snapshot}=boundFixture();const plan=x.planBoundCommerceEdit(snapshot,{compareAtPrice:null,taxable:false,requiresShipping:false});assert.deepEqual(plan.request.variables.variants[0],{id:snapshot.identity.variantGid,compareAtPrice:null,taxable:false,inventoryItem:{requiresShipping:false}});});
test('status isolated; unrelated existing unusual compare price never blocks hiding',()=>{const {snapshot}=boundFixture();snapshot.fields.compareAtPrice='400.00';const plan=x.planBoundCommerceEdit(snapshot,{status:'DRAFT'});assert.deepEqual(plan.request.variables,{product:{id:snapshot.identity.productGid,status:'DRAFT'}});assert.throws(()=>x.planBoundCommerceEdit(snapshot,{status:'DRAFT',price:'600'}));});
test('reject malformed nulls/unknown authority or inventory fields/no-op/invalid price',()=>{const {snapshot}=boundFixture();for(const patch of [null,{}, {price:null},{taxable:null},{status:null},{tracked:false},{available:4},{price:'0'},{price:'-1'},{price:'500'},{price:'900'}])assert.throws(()=>x.planBoundCommerceEdit(snapshot,patch));});
test('reader exact alias identity and raw nullable values, no stock resolver',()=>{const f=boundFixture(),s=reader.parseBoundCommerceRead(f.raw,f.identity);assert.equal(s.identity.exactGallerySku,'EXACT-001-TU');assert.equal(s.identity.sku,'EXACT001');assert.equal(s.fields.barcode,null);assert.equal(s.tracked,true);assert.doesNotMatch(reader.BOUND_COMMERCE_QUERY,/inventoryLevels|locations\(|quantities\(/);});
test('reader rejects missing/null/partial/mixed identities and detects protected changes',()=>{const f=boundFixture(),original=reader.parseBoundCommerceRead(f.raw,f.identity);for(const mutate of [r=>r.product=null,r=>r.product.variants.nodes.push(r.product.variants.nodes[0]),r=>r.product.variants.nodes[0].sku='OTHER',r=>r.product.media.pageInfo.hasNextPage=true,r=>r.product.variants.nodes[0].inventoryItem.tracked=null,r=>r.product.media.nodes.push(r.product.media.nodes[0])]){const raw=structuredClone(f.raw);mutate(raw);assert.throws(()=>reader.parseBoundCommerceRead(raw,f.identity));}f.raw.product.descriptionHtml='<p>Changed</p>';assert.notEqual(reader.parseBoundCommerceRead(f.raw,f.identity).protectedHash,original.protectedHash);});
function setup(){const f=boundFixture();let prior=null,current=structuredClone(f.snapshot),lost=false,stageLost=false;const calls=[];const db={from(){return{select(){return this},eq(){return this},abortSignal(){return this},async maybeSingle(){return{data:prior,error:null}}}},rpc(name,args){return{abortSignal:async()=>{calls.push(name);if(name==='read_bound_commerce_identity')return{data:f.identity};if(name==='acquire_shopify_reconciliation_lease'||name==='release_shopify_reconciliation_lease')return{data:true};if(name==='stage_bound_commerce_edit'){const plan=x.planBoundCommerceEdit(args.p_baseline,args.p_patch);prior={id:args.p_id,item_id:args.p_item_id,expected_hash:args.p_expected_hash,patch:args.p_patch,state:'pending',...plan};if(stageLost)throw Error('lost SQL');return{data:prior}}if(name==='dispatch_bound_commerce_edit'){assert.ok(!prior.dispatched);prior.dispatched=true;return{data:prior.request}}if(name==='ack_bound_commerce_edit'){prior.state=prior.dispatched&&p.fingerprint(x.boundCommerceSemantic(args.p_readback))===p.fingerprint(x.boundCommerceSemantic(prior.desired))?'confirmed':'review';prior.readback=args.p_readback;return{data:prior}}throw Error(name)}}}};globalThis.__existingCommerce={read:async()=>structuredClone(current),send:async()=>{calls.push('SEND');current=structuredClone(prior.desired);if(lost)throw Error('lost provider');return{productVariantsBulkUpdate:{userErrors:[]}}}};const edit={id:id(23),itemId:f.identity.itemId,expectedHash:p.fingerprint(f.snapshot),patch:{price:'550.00'}};return{f,db,calls,edit,setCurrent:v=>current=v,loseProvider:()=>lost=true,loseStage:()=>stageLost=true};}
test('actual runtime fresh preflight -> durable stage/dispatch -> one changed write -> readback',()=>enabled(async()=>{const s=setup();const r=await runtime.editExistingCommerce(s.db,s.edit,id(30));assert.equal(r.status,'confirmed');assert.deepEqual(s.calls,['read_bound_commerce_identity','acquire_shopify_reconciliation_lease','stage_bound_commerce_edit','dispatch_bound_commerce_edit','SEND','ack_bound_commerce_edit','release_shopify_reconciliation_lease']);}));
test('stale browser source fails before journal/native write',()=>enabled(async()=>{const s=setup();s.setCurrent({...s.f.snapshot,fields:{...s.f.snapshot.fields,price:'501.00'}});await assert.rejects(runtime.editExistingCommerce(s.db,s.edit,id(30)),/STALE/);assert.ok(!s.calls.includes('SEND'));assert.ok(!s.calls.includes('stage_bound_commerce_edit'));}));
test('accepted provider response loss resumes read-only with same immutable command ID',()=>enabled(async()=>{const s=setup();s.loseProvider();assert.equal((await runtime.editExistingCommerce(s.db,s.edit,id(30))).status,'pending');assert.equal((await runtime.editExistingCommerce(s.db,s.edit,id(30))).status,'confirmed');assert.equal(s.calls.filter(x=>x==='SEND').length,1);assert.equal(s.calls.filter(x=>x==='dispatch_bound_commerce_edit').length,1);}));
test('uncertain durable stage never turns recovery into first/repeated external dispatch',()=>enabled(async()=>{const s=setup();s.loseStage();await assert.rejects(runtime.editExistingCommerce(s.db,s.edit,id(30)));assert.equal((await runtime.editExistingCommerce(s.db,s.edit,id(30))).status,'review');assert.ok(!s.calls.includes('SEND'));}));
test('same command cannot recover with changed patch',()=>enabled(async()=>{const s=setup();s.loseProvider();await runtime.editExistingCommerce(s.db,s.edit,id(30));await assert.rejects(runtime.editExistingCommerce(s.db,{...s.edit,patch:{price:'560.00'}},id(30)),/REUSED/);assert.equal(s.calls.filter(x=>x==='SEND').length,1);}));
test('default-off rejects before any DB/native side effect',async()=>{const prior=process.env.SHOPIFY_GALLERY_PUBLISH_MODE;delete process.env.SHOPIFY_GALLERY_PUBLISH_MODE;try{await assert.rejects(runtime.editExistingCommerce({},null,id(30)),/NOT_ENABLED/)}finally{if(prior!==undefined)process.env.SHOPIFY_GALLERY_PUBLISH_MODE=prior;}});
