import test from 'node:test';import assert from 'node:assert/strict';
import{mod,stripped,galleryUrl,readyUrl,ready,fixture,id,owner,now,url}from'./helpers/media-planning-fixture.mjs';
Error.stackTraceLimit=0;
const api=await import(mod(`import{createHash}from'node:crypto';import{galleryRawToSnapshot}from'${galleryUrl}';import{mediaReadToSnapshot}from'${readyUrl}';${stripped('media-planning-observation')}`));
function f(){const v=fixture(),calls=[];const deps={now:()=>now,capture:async(i,u,d)=>{calls.push(['decode',i,u,d]);return v.bytes;},shopify:async()=>v.read,gallery:()=>({read:async()=>v.raw})};return {...v,calls,deps,run:()=>api.captureMediaPlanningPair(v.context,owner,now+30000,deps)};}
test('actual mappers preserve both independent baselines and immutable provenance',async()=>{const x=f(),out=await x.run();assert.deepEqual(out.pair,x.pair);assert.deepEqual(out.refs,x.refs);assert.equal(out.proofs.length,2);assert.equal(x.calls.length,1,'same bytes at same URL decode once');assert.deepEqual(x.calls[0][1],id);});
test('planning consumes metadata only and never retains or reads source byte buffers',async()=>{
 const x=f();Object.defineProperty(x.bytes,'bytes',{get(){throw Error('PLANNING_MUST_NOT_READ_OR_RETAIN_BYTES');},enumerable:true});
 const out=await x.run();assert.deepEqual(out.pair,x.pair);assert.equal(x.calls.length,1);
 assert.ok(out.proofs.every(p=>!Object.hasOwn(p.proof,'bytes')));
});
test('new Gallery angle derives own UUID key, never existing Shopify positional identity',async()=>{const x=f(),a={...x.raw.angles[0],id:'a0000000-0000-4000-8000-000000000007',angle_order:2,image_path:url+'?new=1'};x.raw.angles.push(a);const out=await x.run();assert.equal(out.refs[2].key,`g-angle:${a.id}`);assert.notEqual(out.refs[2].key,'existing');assert.equal(out.pair.gallery.assets.length,2);assert.equal(out.pair.shopify.assets.length,1);assert.match(out.proofs.find(p=>p.key===out.refs[2].key).evidenceId,/^g:[a-f0-9]{64}$/);});
test('changed bytes on existing angle retain key but create new verified lineage',async()=>{const x=f();x.bytes.sha256='c'.repeat(64);const out=await x.run();assert.equal(out.pair.gallery.assets[0].key,'existing');assert.equal(out.pair.gallery.assets[0].contentId,'c'.repeat(64));assert.notEqual(out.pair.gallery.assets[0].evidenceId,'g-existing');});
test('known clone preserves original content identity from server receipt',async()=>{const x=f();for(const p of x.context.provenance)p.content_id='d'.repeat(64);for(const side of ['gallery','shopify'])x.context.baselines[side].assets[0].contentId='d'.repeat(64);x.context.provenance[1].proof.operationId='a0000000-0000-4000-8000-000000000009';const out=await x.run();assert.equal(out.pair.shopify.assets[0].contentId,'d'.repeat(64));assert.equal(out.pair.gallery.assets[0].contentId,'d'.repeat(64));});
test('conflicting same-product provenance is a hold, never a guessed merge',async()=>{const x=f();x.context.provenance.push({...structuredClone(x.context.provenance[0]),evidence_id:'other',content_id:'f'.repeat(64)});await assert.rejects(x.run(),/AMBIGUOUS_LINEAGE/);});
test('same Shopify MediaImage previously assigned multiple keys is held',async()=>{const x=f();x.context.provenance.push({...structuredClone(x.context.provenance[1]),evidence_id:'other',asset_key:'other'});await assert.rejects(x.run(),/AMBIGUOUS_LINEAGE/);});
test('multiple cover-equal angles without prior matching identity are held',async()=>{const x=f();x.context.galleryRefs=[];x.raw.angles.push({...x.raw.angles[0],id:'a0000000-0000-4000-8000-000000000007',angle_order:2});await assert.rejects(x.run(),/COVER_AMBIGUOUS/);});
test('cover previously shared with angle can become independent without hijacking angle',async()=>{const x=f();x.raw.item.cover_image_path=url+'?cover=1';const out=await x.run();assert.equal(out.refs[0].key,`g-cover:${id.itemId}`);assert.equal(out.refs[1].key,'existing');assert.equal(out.pair.gallery.assets.length,2);});
test('new Shopify media key derives ID, not nearby title/position/filename',async()=>{const x=f();x.product.media.nodes[0].id='gid://shopify/MediaImage/999';const fresh=ready.parseMediaReadResponse({data:{product:x.product}},id);x.deps.shopify=async()=>fresh;const out=await x.run();assert.equal(out.pair.shopify.assets[0].key,'s-media:999');assert.equal(out.pair.gallery.assets[0].key,'existing');});
test('Shopify image size must match actual decoded pixels',async()=>{const x=f();x.read.images[0].width++;await assert.rejects(x.run(),/IMAGE_DIMENSIONS_CHANGED/);});
test('Gallery change during remote decoding blocks publication of snapshot',async()=>{const x=f();x.deps.gallery=()=>({read:async()=>({...x.raw,revision:'e'.repeat(64)})});await assert.rejects(x.run(),/SOURCE_CHANGED_DURING_READ/);});
test('Shopify change during remote decoding blocks publication of snapshot',async()=>{const x=f();let n=0;x.deps.shopify=async()=>({...x.read,fingerprint:++n===1?x.read.fingerprint:'e'.repeat(64)});await assert.rejects(x.run(),/SOURCE_CHANGED_DURING_READ/);});
test('expired budget performs zero source reads',async()=>{const x=f();await assert.rejects(api.captureMediaPlanningPair(x.context,owner,now,x.deps),/TIME_BUDGET/);assert.equal(x.calls.length,0);});
