import test from'node:test';import assert from'node:assert/strict';import{mod,stripped,galleryUrl,fixture,id,owner,now,opId}from'./helpers/media-planning-fixture.mjs';
Error.stackTraceLimit=0;
const api=await import(mod(`import{randomUUID}from'node:crypto';import{parseGalleryMediaRaw}from'${galleryUrl}';${stripped('media-bootstrap')}`));
function f(){const v=fixture(),calls=[],state={initialized:false,enabled:false,scopes:['write_products','write_files'],env:{VERCEL_ENV:'production',SHOPIFY_MEDIA_SYNC:'enabled_v1'}},proofs=v.context.provenance.map(p=>({side:p.side,key:p.asset_key,evidenceId:p.evidence_id,contentId:p.content_id,proof:p.proof}));
 const observed={pair:v.pair,proofs,refs:v.refs};observed.pair.shopify.assets[0].key='independent-shop';observed.proofs[1].key='independent-shop';
 const db={rpc(name,args){calls.push({name,args});return{abortSignal(){if(state.error&&name==='initialize_toptik_media_observation')return Promise.reject(state.error);return Promise.resolve({data:name==='read_toptik_media_bootstrap_context'?{identity:id,galleryRaw:v.raw,initialized:state.initialized,enabled:state.enabled,approvalId:state.initialized?opId:null}:name==='set_toptik_media_enabled'?{enabled:true}:{initialized:true,approvalId:args.p_approval_id,enabled:args.p_enable},error:null});}};}};
 const deps={client:db,now:()=>now,environment:state.env,transport:()=>({acquire:async()=>{calls.push('acquire');return{owner,expiresAt:now+120000};},release:async()=>calls.push('release')}),scopes:async()=>({scopes:state.scopes}),capture:async(c,o,d)=>{calls.push({name:'capture',args:[c,o,d]});return observed;}};
 return{v,calls,state,observed,deps,run:enable=>api.bootstrapProductionMedia(id.productId,enable,now+45000,deps)};}
test('real decoded unique byte equality establishes shared key; source structures unchanged',()=>{const x=f(),before=structuredClone(x.observed),r=api.matchBootstrapExactBytes(x.observed);assert.equal(r.pair.shopify.assets[0].key,r.pair.gallery.assets[0].key);assert.equal(r.proofs[1].key,r.proofs[0].key);assert.deepEqual(x.observed,before);});
test('different bytes/dimensions or duplicate hash stays independent, never names/position mapping',()=>{for(const edit of[x=>x.pair.shopify.assets[0].contentId='f'.repeat(64),x=>x.proofs[1].proof.width++,x=>x.pair.gallery.assets.push({...x.pair.gallery.assets[0],key:'duplicate'})]){const x=f();edit(x.observed);const r=api.matchBootstrapExactBytes(x.observed);assert.equal(r.pair.shopify.assets[0].key,'independent-shop');}});
test('initialization is private baseline+raw observation atomic RPC, default disabled',async()=>{const x=f(),r=await x.run(false);assert.equal(r.enabled,false);assert.equal(r.sharedExactImages,1);const capture=x.calls.find(c=>c.name==='capture').args[0];assert.deepEqual(capture.baselines.gallery.assets,[]);assert.deepEqual(capture.provenance,[]);const write=x.calls.find(c=>c.name==='initialize_toptik_media_observation');assert.equal(write.args.p_enable,false);assert.equal(write.args.p_pair.gallery.assets[0].alt,'bag');assert.equal(x.calls.at(-1),'release');assert.equal(x.calls.filter(c=>c.name==='initialize_toptik_media_observation').length,1);});
test('automatic enabled admission requires explicit production flag and fresh write scopes',async()=>{const x=f();assert.equal((await x.run(true)).enabled,true);const y=f();delete y.state.env.SHOPIFY_MEDIA_SYNC;await assert.rejects(y.run(true),/ACTIVATION_DISABLED/);assert.deepEqual(y.calls,[]);const z=f();z.state.scopes=['write_products'];await assert.rejects(z.run(true),/SCOPE_REQUIRED/);assert.equal(z.calls.some(c=>c.name==='initialize_toptik_media_observation'),false);assert.equal(z.calls.at(-1),'release');});
test('existing initialization never replaces baseline/provenance or disables enabled record',async()=>{const x=f();x.state.initialized=true;x.state.enabled=true;const r=await x.run(false);assert.equal(r.enabled,true);assert.equal(r.alreadyInitialized,true);assert.equal(x.calls.some(c=>c.name==='capture'||c.name==='initialize_toptik_media_observation'),false);});
test('explicit enable existing private initialization references exact immutable approval',async()=>{const x=f();x.state.initialized=true;const r=await x.run(true);assert.equal(r.enabled,true);assert.equal(x.calls.find(c=>c.name==='set_toptik_media_enabled').args.p_approval_id,opId);assert.equal(x.calls.some(c=>c.name==='capture'),false);});
test('lost initial transaction response is never blindly retried',async()=>{const x=f();x.state.error=Error('secret');await assert.rejects(x.run(true),/^Error: MEDIA_BOOTSTRAP_RPC_FAILED$/);assert.equal(x.calls.filter(c=>c.name==='initialize_toptik_media_observation').length,1);assert.equal(x.calls.at(-1),'release');});
test('preview, malformed identity and expired budget have zero IO',async()=>{const x=f();x.state.env.VERCEL_ENV='preview';await assert.rejects(x.run(false),/PRODUCTION_REQUIRED/);x.state.env.VERCEL_ENV='production';await assert.rejects(api.bootstrapProductionMedia('bad',false,now+100,x.deps),/INPUT_INVALID/);await assert.rejects(api.bootstrapProductionMedia(id.productId,false,now,x.deps),/TIME_BUDGET/);assert.deepEqual(x.calls,[]);});
