import test from 'node:test';import assert from 'node:assert/strict';
import{mod,stripped,coreUrl,galleryUrl,fixture,id,owner,opId,now}from'./helpers/media-planning-fixture.mjs';
Error.stackTraceLimit=0;
const api=await import(mod(`import{randomUUID}from'node:crypto';import{mediaSnapshotFingerprint}from'${coreUrl}';import{parseGalleryMediaRaw}from'${galleryUrl}';const createSupabaseServiceRoleClient=()=>{throw Error('SECRET_FACTORY');};${stripped('media-planning-rpc')}`));
function f(handler){const calls=[],signals=[],client={rpc(name,args){calls.push({name,args});return{abortSignal(signal){signals.push(signal);return Promise.resolve().then(()=>handler(name,args));}};}};return{calls,signals,port:api.createMediaPlanningRpc(id.productId,{client,now:()=>now})};}
test('context uses fixed service RPC and checks real raw identity',async()=>{const c=fixture().context,x=f(()=>({data:c}));assert.deepEqual(await x.port.context(owner,now+1000),c);assert.deepEqual(x.calls[0],{name:'read_toptik_media_planning_context',args:{p_product_gid:id.productId,p_lease_owner:owner}});});
for(const [label,edit]of[['product',c=>c.identity.productId='gid://shopify/Product/999'],['raw SKU',c=>c.galleryRaw.item.catalog_number='OTHER'],['proof owner',c=>c.provenance[0].product_gid='gid://shopify/Product/999'],['unsafe context size',c=>c.steps=[{},{},{}]]])test(`context rejects ${label}`,async()=>{const c=fixture().context;edit(c);const x=f(()=>({data:c}));await assert.rejects(x.port.context(owner,now+1000),/IDENTITY|INVALID/);});
test('fixed register and reservation pass copied proof/plan and server-generated UUID',async()=>{const x=f(name=>({data:name==='register_toptik_media_provenance'?true:{operationId:opId}})),v=fixture();await x.port.register(owner,[],now+1000);await x.port.reserve(owner,1,v.pair,{patches:[],orders:[],conflicts:[]},now+1000);assert.equal(x.calls[0].name,'register_toptik_media_provenance');assert.equal(x.calls[1].args.p_expected_version,1);assert.match(x.calls[1].args.p_operation_id,/^[a-f0-9-]{36}$/);assert.deepEqual(x.calls[1].args.p_current,v.pair);});
test('begin accept commit pin operation, step, owner and fresh pair',async()=>{const x=f(()=>({data:{status:'verified'}})),v=fixture();await x.port.begin(owner,opId,2,v.pair,now+1000);await x.port.accept(owner,opId,2,v.pair,now+1000);await x.port.commit(owner,opId,v.pair,now+1000);assert.deepEqual(x.calls.map(c=>c.name),['begin_toptik_media_step','accept_toptik_media_readback','commit_toptik_media_operation']);for(const c of x.calls){assert.equal(c.args.p_operation_id,opId);assert.equal(c.args.p_lease_owner,owner);assert.equal(c.args.p_product_gid,id.productId);}});

test('fresh final readback pins exact operation, pair and guard without exposing an execution permit',async()=>{const x=f(()=>({data:{status:'verified',mayExecute:false}})),v=fixture(),guard={sourceFingerprint:'a'.repeat(64),target:v.pair.shopify,observedAt:new Date(now).toISOString()};await x.port.acceptFinal(owner,opId,2,v.pair,guard,now+1000);assert.equal(x.calls[0].name,'accept_toptik_media_final_readback');assert.deepEqual(x.calls[0].args.p_guard,guard);assert.deepEqual(x.calls[0].args.p_observed,v.pair);assert.equal(x.calls[0].args.p_operation_id,opId);assert.equal(x.calls[0].args.p_lease_owner,owner);for(const bad of [{...guard,target:{...guard.target,identity:{...id,productId:'gid://shopify/Product/999'}}},{...guard,observedAt:'bad'}])await assert.rejects(x.port.acceptFinal(owner,opId,2,v.pair,bad,now+1000),/GUARD_INVALID/);assert.equal(x.calls.length,1);});
test('Gallery removal requires server actor and fixed origin; Shopify proof preserved',async()=>{const x=f(()=>({data:{}}));await x.port.removal(owner,'gallery','a','a'.repeat(64),{actorType:'admin_panel_token',actorId:'configured-admin-panel'},now+1000);assert.equal(x.calls[0].args.p_auth_evidence.origin,'https://landing.toptik.co.il');assert.equal(x.calls[0].args.p_auth_evidence.kind,'authenticated_editor');const event={kind:'signed_shopify_event',eventId:opId,deliveryId:'signed'};await x.port.removal(owner,'shopify','a','a'.repeat(64),event,now+1000);assert.deepEqual(x.calls[1].args.p_auth_evidence,event);});
test('error details masked, no blind RPC retries',async()=>{const x=f(()=>({error:{message:'password SECRET'}}));await assert.rejects(x.port.context(owner,now+1000),/^Error: MEDIA_PLANNING_RPC_FAILED$/);assert.equal(x.calls.length,1);});
test('expired and malformed owner never contact DB',async()=>{const x=f(()=>({data:null}));await assert.rejects(x.port.context(owner,now),/TIME_BUDGET/);await assert.rejects(x.port.context('bad',now+1000),/ID_INVALID/);assert.equal(x.calls.length,0);});
